/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        outline: "#988d98",
        "on-surface-variant": "#cfc3ce",
        "secondary-fixed": "#ffe088",
        "inverse-primary": "#774f88",
        "surface-container-lowest": "#160722",
        "secondary-container": "#af8d11",
        "primary-fixed-dim": "#e6b5f6",
        "on-background": "#f2daff",
        "error-container": "#93000a",
        error: "#ffb4ab",
        "surface-dim": "#1c0d27",
        "primary-container": "#2e073f",
        "surface-container-low": "#241530",
        "on-secondary-fixed": "#241a00",
        tertiary: "#e7b4ff",
        "tertiary-fixed": "#f5d9ff",
        surface: "#1c0d27",
        "tertiary-container": "#2f0048",
        "surface-bright": "#43334f",
        "secondary-fixed-dim": "#e9c349",
        "surface-container": "#281934",
        "on-secondary-container": "#342800",
        "on-tertiary-container": "#b35be5",
        "on-tertiary": "#4f0076",
        "on-primary-fixed": "#2f0840",
        "tertiary-fixed-dim": "#e7b4ff",
        primary: "#e6b5f6",
        background: "#1c0d27",
        "inverse-on-surface": "#3a2a46",
        secondary: "#e9c349",
        "surface-container-highest": "#3f2e4b",
        "on-primary-container": "#9f73af",
        "on-secondary-fixed-variant": "#574500",
        "primary-fixed": "#f8d8ff",
        "outline-variant": "#4c444d",
        "on-surface": "#f2daff",
        "on-error-container": "#ffdad6",
        "surface-variant": "#3f2e4b",
        "on-primary-fixed-variant": "#5e376e",
        "surface-container-high": "#33233f",
        "on-tertiary-fixed": "#30004a",
        "surface-tint": "#e6b5f6",
        "on-tertiary-fixed-variant": "#7008a2",
        "inverse-surface": "#f2daff",
        "on-primary": "#462056",
        "on-secondary": "#3c2f00",
        "on-error": "#690005",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "section-gap": "120px",
        gutter: "24px",
        "margin-desktop": "80px",
        "container-max": "1440px",
        "margin-mobile": "20px",
      },
      fontFamily: {
        "body-md": ["Montserrat", "sans-serif"],
        "headline-sm": ["Playfair Display", "serif"],
        "display-lg-mobile": ["Playfair Display", "serif"],
        "body-lg": ["Montserrat", "sans-serif"],
        "label-caps": ["Montserrat", "sans-serif"],
        "headline-md": ["Playfair Display", "serif"],
        "display-lg": ["Playfair Display", "serif"],
      },
      fontSize: {
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-sm": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "display-lg-mobile": ["40px", { lineHeight: "48px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.1em", fontWeight: "600" }],
        "headline-md": ["32px", { lineHeight: "40px", fontWeight: "600" }],
        "display-lg": ["64px", { lineHeight: "72px", letterSpacing: "-0.02em", fontWeight: "700" }],
      },
    },
  },
  plugins: [],
};
